# Generated by Django 4.2 on 2023-05-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='involvedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.IntegerField()),
                ('productName', models.CharField(max_length=200)),
                ('entityID', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='entity',
            name='id',
        ),
        migrations.AddField(
            model_name='entity',
            name='password',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='bID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
