# Generated by Django 4.2 on 2023-05-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrec', '0002_involvedentity_remove_entity_id_entity_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='involvedentity',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='productslist',
            name='id',
        ),
        migrations.AlterField(
            model_name='productslist',
            name='productID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
