# Generated by Django 4.2 on 2023-05-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrec', '0003_remove_involvedentity_productname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='bID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='productID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
